新增wget错误判定

diff --git a/.github/workflows/Update.yml b/.github/workflows/Update.yml
--- a/.github/workflows/Update.yml
+++ b/.github/workflows/Update.yml
@@ -231,6 +231,10 @@ jobs:
     - name: Bilibili启动时切换为直连
       run : |
         wget https://codeberg.org/ddgksf2013/Cuttlefish/raw/branch/master/Script/bilibili_startup_direct.js -O bilistart.tmp
+        if [ $? -ne 0 ]; then
+          echo "[ERROR] 正常にダウンロードできませんでした"
+          exit 1
+        fi
         awk '
         {
           gsub("DomesticMedia","📺 Bilibili");
